### ISSUE TITLE
make_pair_copula_store(0) causes a segfault

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#164]
actually called by calling vinecop size_t ctor with bicop_family.indep that evaluates to 0... (in Python; in C++ this is type-safe an enum class)

**Comment by tvatter** [comment]
I don't understand. So is this an issue with Python or C++?

**Comment by slayoo** [comment]
Sorry,

in C++, this is a make_pair_copula_store() issue
in Python, this is a make_pair_copula_store() **and** vinecop ctor issue

**Comment by tvatter** [comment]
OK, but make_pair_copula_store(0) does not make sense (you can't have a distribution with 0 random variables), and as you know we haven't been very strict with the sanity checks. A simple solution would be to throw an error if the parameter is smaller than 1 (actually, smaller than 2 because even make_pair_copula_store(1) does not really make sense).

**Comment by slayoo** [comment]
perfect (i.e., to throw an error)

**Comment by tvatter** [comment]
See #166
