### ISSUE TITLE
Improved structure selection

### ISSUE THREAD

**Issue by tnagler** [vinecopulib/vinecopulib#452]
We agreed (#360) that we want to allow for partially specified structures. While we're at it, we should also allow for specialized D- and C-vine selection methods. Let's collect our ideas here:
(Repeating what's in #360)_
- A unified `select()` method as  sounds like a very good idea. We can soft deprecate the specialized methods.
- Idea for the API: it would be convenient to provide a partial structure as a truncated `struct_array`. We could do `bool partial` and complete everything above the `trunc_lvl`. We still have a `trunc_lvl` slot in `FitControls` for setting a truncation level.

More thoughts:
- We should have another `FitControlVinecop` member specifying R/D/C-vine.  Maybe as an `enum` (related to #158).
- In some cases, people may want to specify a (partial) order of variables in a D/C-vine. Is that worth an option in the library? (My opinion: no).

**Comment by tvatter** [comment]
Just as a reminder for myself, I'm implementing the behavior that we discussed when `select_partial = TRUE`:

1. We pass the data only implies that we select everything up to `controls.trunc_lvl`.
2. If a structure is specified, the behavior is dictated by `controls.trunc_lvl`. 
     a. If `controls.trunc_lvl < structure.trunc_lvl`, only the pairs up to `controls.trunc_lvl` are selected.
     b. If `controls.trunc_lvl > structure.trunc_lvl`, the partial selection kicks in.

**Comment by tvatter** [comment]
Note that the 2.a. is different from the current behavior... I just thought that it would be better to assume that one parameter always has precedence over the other.

**Comment by tnagler** [comment]
Partial selection done with #457, D- and C-vine selection methods still missing.

**Comment by tvatter** [comment]
So, related to  D- and C-vine selection:

- For C-vine selection, we can list all possible central nodes and test the best, it's not a huge computational cost.
- For D-vine selection, this is obviously no possible, but we can do a shortest path instead of an mst.

Now, the question is the API: should we add a data member to `FitControlsVinecop` or create two additional `select` methods? 

- Regarding adding a data member: the API is unified and we're burying a feature that no one uses anyway in `FitControlsVinecop`. The main drawback IMO is that we need to decide what happens in the constructors when a structure is also passed as input. We can also throw an error in `select` if `FitControlsVinecop` has a `type = "C"` or `type = "D"` and the structure's truncation level is not zero. But this is a bit cumbersome.

- Regarding adding `select_cvine` and `select_dvine`: simplify the issues above, but the API is less unified, and we would need an additional argument to the constructor with data only in order to know which `select` to use.

Other ideas?

**Comment by tnagler** [comment]
We agreed that it's not useful enough to warrant bloating the library. Closing until somebody convinces us otherwise.
