### ISSUE TITLE
Enable additional parallelism?

### ISSUE THREAD

**Issue by sdressler** [vinecopulib/vinecopulib#553]
Hi,

I am using `vinecopulib` in a project to generate synthetic data with actual data as the foundation. First of all, thanks for providing the library. It feels very robust and works very well.

Since my input matrices can be rather large (up to 100 columns with 100k+ rows), I investigated where performance goes. I stumbled over `Bicop::select` (in `include/vinecopulib/bicop/implementation/class.ipp`) which effectively loops over `std::vector<Bicop>`. As far as I understand the implementation, this piece is parallelizable. I also see

```c++
tools_thread::ThreadPool pool(controls.get_num_threads());
pool.map(fit_and_compare, bicops);
```

However, I noticed that `controls.get_num_threads()` will always return zero caused by `include/vinecopulib/vinecop/implementation/tools_select.ipp`, lines 993:997:

```c++
// make sure that Bicop.select() doesn't spawn new threads
size_t num_threads = controls_.get_num_threads();
controls_.set_num_threads(0);
pool_.map(select_pc, boost::edges(tree));
pool_.wait();
controls_.set_num_threads(num_threads);
```

Now, I wonder why that is the case since `Bicop::select` seems encapsulated enough to have it run in parallel.

Any pointers are appreciated.

Many thanks,
Sebastian

**Comment by tnagler** [comment]
The parallelization happens one level above, i.e., over the different pair-copulas in a tree level. With more than a few variable this makes more sense than parallelizing over copula families (which has no effect if there's only few families allowed).

100 variables and 100k+ observations is a fairly large problem. First, there are 100 * 99 / 2 = 4500 pair-copulas in the model. In such large problems, the first step should be to look for sparse models via truncation or thresholding, see [this paper](https://arxiv.org/abs/1801.09739). Second, the nonparametric estimators for the pair-copula are relatively slow for such a large number of rows. I'd suggest to start with a small selection of simple parametric models and increase complexity later if necessary. For example:
``` cpp 
FitControlsVinecop controls(bicop_families::one_par);  // or bicop_families::parametric
controls.set_select_trunc_lvl(true);    // search for truncation level
// or: controls.set_trunc_lvl(2);    // fixes truncation level at two
controls.set_num_threads(16);  // parallelize with 16 threads
Vinecop vine_fit(data, controls);
```
([API docs](https://vinecopulib.github.io/vinecopulib/classvinecopulib_1_1_fit_controls_vinecop.html))

**Comment by sdressler** [comment]
Thanks for the prompt reply. I should have mentioned that I am already configuring the number of threads. I also picked a fixed selection of families (Gauss, Students t, BBs). Most time is spent on Students t. I hardcoded the parameter above to >0 (because no matter what I set as `num_threads` it’ll be changed to 0 at that point) and found that it gives me a 2x speedup. For the test-matrix, Students t was the preferred compilation eventually. 

I guess, it’d be helpful to have this particular setting configurable separately. I am willing to do a PR if this is helpful, but wanted to first reassure that, by adding parallelization at that point, nothing breaks. 

Many thanks,
Sebastian

**Comment by tnagler** [comment]
On how many threads do you run? I

I'm not too excited about a seperate option to specify threads, mainly because it would be much more annoying to set things up. It's certainly possible though.

I see more potential for a heuristic that internally decides where tasks are split, but that requires some thought.

(Anyway, truncating the vine should give you a significant speedup.)

**Comment by sdressler** [comment]
That specific model only has 2 columns but about 100k rows, and I give it 8 threads which are briefly used. For that particular override I gave it 6 threads so that every bicop gets one thread.

I’m work through the paper you linked, thanks for that. The full process with multiple matrixes takes about three days atm, so limiting it will make a lot of sense. 

Another thought on the parallelization: since it effectively is a graph, one could use Intel
TBB to schedule (or any other graph scheduler). 

I was also looking into caching results for Students t since I noticed that `nu` gets potentially repeated. This seems to be problem specific, however.

**Comment by tnagler** [comment]
For 2 columns, you can use `Bicop` models directly. There, parallelization is over the families by default. Of course, there may be reasons to use `Vinecop` nevertheless, but such cases could be caught easily by a heuristic (e.g.: if num_cores > num_columns: parallelize over pair-copulas, else parallelize over families).

One could use a graph scheduler, but it's unlikely to improve much. For the most part, this is an embarrassingly parallel problem.

One further option for you would `FitControlsVinecop(bicop_families::itau, "itau")`. This uses inversion of Kendall's tau instead of maximum likelihood estimation, but is only possible for one-parameter families and the Student-t copulas (where then only `nu` is optimized very roughly via MLE). Normally this is much faster.

**Comment by tnagler** [comment]
Unless you come up with a much smarter solution I'll probably just go with the version in #555:

``` cpp
// make sure that Bicop.select() doesn't spawn too many new threads
size_t num_threads = controls_.get_num_threads();
controls_.set_num_threads(num_threads / boost::num_edges(tree));
pool_.map(select_pc, boost::edges(tree));
pool_.wait();
controls_.set_num_threads(num_threads);
```

**Comment by sdressler** [comment]
I think that's a good compromise between the two extremes.
